### ISSUE TITLE
404 page not loading on live site

### ISSUE THREAD

**Issue by discoform** [wurmlab/sequenceserver-website#3]
It appears that 404's are not being directed to the site's 404 error page.

Local testing works as expected. Here's what I see as a 404 error using localhost:

![Screen Shot 2021-09-09 at 5 10 29 PM](https://user-images.githubusercontent.com/23062181/132778531-7e564882-883f-48c8-85be-a4c91ac786c5.png)

However, on the live site I see an `nginx` error like this:

![Screen Shot 2021-09-09 at 5 13 36 PM](https://user-images.githubusercontent.com/23062181/132778578-cdb6e6f5-74dd-4d34-80a9-b11d37162164.png)

I'm not sure this is something I can address from here. Could it be a configuration issue with `nginx`?

**Comment by yeban** [comment]
Fixed. Thanks! The issue was the Nginx config indeed.
